In [42]:
import torch

In [2]:
num_images = 3
images = torch.zeros(num_images,512,512)
for i in range(num_images):
    images[i,:,:] = torch.randn(512,512)

images = images.reshape(512,512,num_images)

In [3]:
cat = images[:,:,0]
print('cat.device =',cat.device)
print('cat.shape =', cat.shape)

cat.device = cpu
cat.shape = torch.Size([512, 512])


In [4]:
cat3 = torch.unsqueeze(cat,2)
print('cat.shape =', cat3.shape)

cat.shape = torch.Size([512, 512, 1])


In [5]:
x = torch.randn(3,4,5)
x.shape

torch.Size([3, 4, 5])

In [6]:
y = torch.permute(x)

TypeError: permute() missing 1 required positional arguments: "dims"

In [9]:
t = torch.arange(6).reshape(2, 3)
t,t.shape


(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]))

In [10]:
t.permute(1,0)

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [13]:
t.reshape(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [23]:
t,t.shape

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]))

In [26]:
u = t.reshape(2,3,1)
u

tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])

In [30]:
u.expand(2,3,4)

tensor([[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5]]])

In [33]:
t = torch.arange(15).reshape(3,5)
t

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [40]:
t.sum(dim=0)

tensor([15, 18, 21, 24, 27])

In [36]:
t[:,0]

tensor([ 0,  5, 10])

In [43]:
t.dim

<function Tensor.dim>

In [50]:
t = torch.arange(15,dtype=torch.float).reshape(3,5)
t

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [51]:
t.sum(dim=0)

tensor([15., 18., 21., 24., 27.])

In [52]:
t.sum(dim=0).expand(3,5)

tensor([[15., 18., 21., 24., 27.],
        [15., 18., 21., 24., 27.],
        [15., 18., 21., 24., 27.]])

In [105]:
t = torch.tensor(torch.arange(15,dtype=torch.float).reshape(3,5),requires_grad=True)
u = torch.tensor(torch.arange(15,dtype=torch.float).reshape(3,5),requires_grad=True)

t,t.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3741574789.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t = torch.tensor(torch.arange(15,dtype=torch.float).reshape(3,5),requires_grad=True)
/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3741574789.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  u = torch.tensor(torch.arange(15,dtype=torch.float).reshape(3,5),requires_grad=True)


(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.]], requires_grad=True),
 None)

In [106]:
v = t * u
v

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.]], grad_fn=<MulBackward0>)

In [107]:
s = v.sum(dim=(0,1))
s,s.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/2427823174.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  s,s.grad


(tensor(1015., grad_fn=<SumBackward1>), None)

In [108]:
s.backward()
s.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/2815799162.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  s.grad


In [97]:
v

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.]], grad_fn=<MulBackward0>)

In [109]:
t.grad,u.grad,v.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/337251670.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  t.grad,u.grad,v.grad


(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.]]),
 None)

In [110]:
v.requires_grad

True

In [111]:
v.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3640305849.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  v.grad
