In [1]:
import torch

In [2]:
num_images = 3
images = torch.zeros(num_images,512,512)
for i in range(num_images):
    images[i,:,:] = torch.randn(512,512)

images = images.reshape(512,512,num_images)

In [3]:
cat = images[:,:,0]
print('cat.device =',cat.device)
print('cat.shape =', cat.shape)

cat.device = cpu
cat.shape = torch.Size([512, 512])


In [4]:
cat3 = torch.unsqueeze(cat,2)
print('cat.shape =', cat3.shape)

cat.shape = torch.Size([512, 512, 1])


In [5]:
x = torch.randn(3,4,5)
x.shape

torch.Size([3, 4, 5])

In [6]:
y = torch.permute(x)

TypeError: permute() missing 1 required positional arguments: "dims"

In [9]:
t = torch.arange(6).reshape(2, 3)
t,t.shape


(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]))

In [10]:
t.permute(1,0)

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [13]:
t.reshape(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [23]:
t,t.shape

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]))

In [26]:
u = t.reshape(2,3,1)
u

tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])

In [30]:
u.expand(2,3,4)

tensor([[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5]]])