In [1]:
import numpy as np

In [2]:
x = np.arange(15).reshape(3,5) + 1
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
np.save('numpy_x',x,allow_pickle=False)

In [4]:
x.dtype

dtype('int64')

In [7]:
y = np.arange(15).reshape(3,5).astype('float32') + 1
np.save('numpy_y',y,allow_pickle=False)
y

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]], dtype=float32)

In [9]:
A = np.arange(15).reshape(5,3) + 1
B = np.arange(21).reshape(3,7) + 1
A,B

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]),
 array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21]]))

In [13]:
C = np.einsum('ij,kh->ih',A,B)
C

array([[ 144,  162,  180,  198,  216,  234,  252],
       [ 360,  405,  450,  495,  540,  585,  630],
       [ 576,  648,  720,  792,  864,  936, 1008],
       [ 792,  891,  990, 1089, 1188, 1287, 1386],
       [1008, 1134, 1260, 1386, 1512, 1638, 1764]])

In [18]:
C = np.einsum('ij,kh',A,B)
C

array([[[[  1,   8,  15],
         [  2,  16,  30],
         [  3,  24,  45]],

        [[  4,  32,  60],
         [  5,  40,  75],
         [  6,  48,  90]],

        [[  7,  56, 105],
         [  8,  64, 120],
         [  9,  72, 135]],

        [[ 10,  80, 150],
         [ 11,  88, 165],
         [ 12,  96, 180]],

        [[ 13, 104, 195],
         [ 14, 112, 210],
         [ 15, 120, 225]]],


       [[[  2,   9,  16],
         [  4,  18,  32],
         [  6,  27,  48]],

        [[  8,  36,  64],
         [ 10,  45,  80],
         [ 12,  54,  96]],

        [[ 14,  63, 112],
         [ 16,  72, 128],
         [ 18,  81, 144]],

        [[ 20,  90, 160],
         [ 22,  99, 176],
         [ 24, 108, 192]],

        [[ 26, 117, 208],
         [ 28, 126, 224],
         [ 30, 135, 240]]],


       [[[  3,  10,  17],
         [  6,  20,  34],
         [  9,  30,  51]],

        [[ 12,  40,  68],
         [ 15,  50,  85],
         [ 18,  60, 102]],

        [[ 21,  70, 119],
         [