In [2]:
import torch

In [2]:
num_images = 3
images = torch.zeros(num_images,512,512)
for i in range(num_images):
    images[i,:,:] = torch.randn(512,512)

images = images.reshape(512,512,num_images)

In [3]:
cat = images[:,:,0]
print('cat.device =',cat.device)
print('cat.shape =', cat.shape)

cat.device = cpu
cat.shape = torch.Size([512, 512])


In [4]:
cat3 = torch.unsqueeze(cat,2)
print('cat.shape =', cat3.shape)

cat.shape = torch.Size([512, 512, 1])


In [5]:
x = torch.randn(3,4,5)
x.shape

torch.Size([3, 4, 5])

In [6]:
y = torch.permute(x)

TypeError: permute() missing 1 required positional arguments: "dims"

In [9]:
t = torch.arange(6).reshape(2, 3)
t,t.shape


(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]))

In [10]:
t.permute(1,0)

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [13]:
t.reshape(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [23]:
t,t.shape

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]))

In [26]:
u = t.reshape(2,3,1)
u

tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])

In [30]:
u.expand(2,3,4)

tensor([[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5]]])

In [33]:
t = torch.arange(15).reshape(3,5)
t

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [40]:
t.sum(dim=0)

tensor([15, 18, 21, 24, 27])

In [36]:
t[:,0]

tensor([ 0,  5, 10])

In [43]:
t.dim

<function Tensor.dim>

In [50]:
t = torch.arange(15,dtype=torch.float).reshape(3,5)
t

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [51]:
t.sum(dim=0)

tensor([15., 18., 21., 24., 27.])

In [52]:
t.sum(dim=0).expand(3,5)

tensor([[15., 18., 21., 24., 27.],
        [15., 18., 21., 24., 27.],
        [15., 18., 21., 24., 27.]])

In [105]:
t = torch.tensor(torch.arange(15,dtype=torch.float).reshape(3,5),requires_grad=True)
u = torch.tensor(torch.arange(15,dtype=torch.float).reshape(3,5),requires_grad=True)

t,t.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3741574789.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t = torch.tensor(torch.arange(15,dtype=torch.float).reshape(3,5),requires_grad=True)
/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3741574789.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  u = torch.tensor(torch.arange(15,dtype=torch.float).reshape(3,5),requires_grad=True)


(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.]], requires_grad=True),
 None)

In [106]:
v = t * u
v

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.]], grad_fn=<MulBackward0>)

In [107]:
s = v.sum(dim=(0,1))
s,s.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/2427823174.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  s,s.grad


(tensor(1015., grad_fn=<SumBackward1>), None)

In [108]:
s.backward()
s.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/2815799162.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  s.grad


In [97]:
v

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.]], grad_fn=<MulBackward0>)

In [109]:
t.grad,u.grad,v.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/337251670.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  t.grad,u.grad,v.grad


(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.]]),
 None)

In [110]:
v.requires_grad

True

In [111]:
v.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3640305849.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  v.grad


In [113]:
z = torch.ones(1)

In [114]:
z

tensor([1.])

In [115]:
z.reshape(4)

RuntimeError: shape '[4]' is invalid for input of size 1

In [130]:
M = torch.tensor(torch.arange(15).reshape(5,3),requires_grad=True,dtype=torch.float32)
v = torch.arange(3,requires_grad=True,dtype=torch.float32)
y = torch.matmul(M,v)
y

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/1768566735.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  M = torch.tensor(torch.arange(15).reshape(5,3),requires_grad=True,dtype=torch.float32)


tensor([ 5., 14., 23., 32., 41.], grad_fn=<MvBackward0>)

In [131]:
M

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]], requires_grad=True)

In [132]:
s = y.sum(0)

In [133]:
s.backward()

In [134]:
M.grad

tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]])

In [140]:
M = torch.tensor(torch.arange(15).reshape(5,3),requires_grad=True,dtype=torch.float32)
v = torch.tensor(torch.arange(9).reshape(3,3),requires_grad=True,dtype=torch.float32)
y = torch.matmul(M,v)

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3613637652.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  M = torch.tensor(torch.arange(15).reshape(5,3),requires_grad=True,dtype=torch.float32)
/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3613637652.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  v = torch.tensor(torch.arange(9).reshape(3,3),requires_grad=True,dtype=torch.float32)


In [141]:
y,y.shape

(tensor([[ 15.,  18.,  21.],
         [ 42.,  54.,  66.],
         [ 69.,  90., 111.],
         [ 96., 126., 156.],
         [123., 162., 201.]], grad_fn=<MmBackward0>),
 torch.Size([5, 3]))

In [139]:
v[1,0]

tensor(3., grad_fn=<SelectBackward0>)

In [143]:
v

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], requires_grad=True)

In [144]:
M

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]], requires_grad=True)

In [147]:
y_ = torch.einsum('ij,bj->bi',M,v)
y_

tensor([[  5.,  14.,  23.,  32.,  41.],
        [ 14.,  50.,  86., 122., 158.],
        [ 23.,  86., 149., 212., 275.]], grad_fn=<ViewBackward0>)

In [148]:
y_.sum(0).sum(0).backward()

In [149]:
M.grad

tensor([[ 9., 12., 15.],
        [ 9., 12., 15.],
        [ 9., 12., 15.],
        [ 9., 12., 15.],
        [ 9., 12., 15.]])

In [157]:
x = torch.arange(8).reshape(2, 1, 2, 1, 2)

In [162]:
torch.squeeze(x,(1,2,3)).shape

torch.Size([2, 2, 2])

In [163]:
a = [1,2,3,4,5]

In [164]:
a[0:3]

[1, 2, 3]

In [165]:
torch.arange(10).reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [6]:
img = torch.arange(1 * 9 * 9).reshape(1,9,9)
ker = torch.arange(1 * 3 * 3).reshape(1,1,3,3)
fet = torch.conv2d(img,ker,stride=1,dilation=1)
fet,fet.shape

(tensor([[[ 528,  564,  600,  636,  672,  708,  744],
          [ 852,  888,  924,  960,  996, 1032, 1068],
          [1176, 1212, 1248, 1284, 1320, 1356, 1392],
          [1500, 1536, 1572, 1608, 1644, 1680, 1716],
          [1824, 1860, 1896, 1932, 1968, 2004, 2040],
          [2148, 2184, 2220, 2256, 2292, 2328, 2364],
          [2472, 2508, 2544, 2580, 2616, 2652, 2688]]]),
 torch.Size([1, 7, 7]))

In [175]:
img = torch.tensor(torch.arange(3 * 9 * 9).reshape(3,9,9),requires_grad=True,dtype=torch.float32)
ker = torch.tensor(torch.arange(3 * 3 * 3).reshape(1,3,3,3),requires_grad=True,dtype=torch.float32)
fet = torch.conv2d(img,ker,stride=2,dilation=1)
x = fet.sum(0).sum(0).sum(0)
x

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3917236685.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  img = torch.tensor(torch.arange(3 * 9 * 9).reshape(3,9,9),requires_grad=True,dtype=torch.float32)
/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/3917236685.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  ker = torch.tensor(torch.arange(3 * 3 * 3).reshape(1,3,3,3),requires_grad=True,dtype=torch.float32)


tensor(897552., grad_fn=<SumBackward1>)

In [194]:

img = torch.tensor(torch.arange(1 * 9 * 9).reshape(1,9,9),requires_grad=True,dtype=torch.float32)
ker = torch.tensor(torch.arange(1 * 3 * 3).reshape(1,1,3,3),requires_grad=True,dtype=torch.float32)
fet = torch.conv2d(img,ker,stride=1,dilation=1)
x = fet.sum(0).sum(0).sum(0)
x.backward()
img.grad,img.grad.shape,ker.grad

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/2392927721.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  img = torch.tensor(torch.arange(1 * 9 * 9).reshape(1,9,9),requires_grad=True,dtype=torch.float32)
/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_9514/2392927721.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  ker = torch.tensor(torch.arange(1 * 3 * 3).reshape(1,1,3,3),requires_grad=True,dtype=torch.float32)


(tensor([[[ 0.,  1.,  3.,  3.,  3.,  3.,  3.,  3.,  2.],
          [ 3.,  8., 15., 15., 15., 15., 15., 12.,  7.],
          [ 9., 21., 36., 36., 36., 36., 36., 27., 15.],
          [ 9., 21., 36., 36., 36., 36., 36., 27., 15.],
          [ 9., 21., 36., 36., 36., 36., 36., 27., 15.],
          [ 9., 21., 36., 36., 36., 36., 36., 27., 15.],
          [ 9., 21., 36., 36., 36., 36., 36., 27., 15.],
          [ 9., 20., 33., 33., 33., 33., 33., 24., 13.],
          [ 6., 13., 21., 21., 21., 21., 21., 15.,  8.]]]),
 torch.Size([1, 9, 9]),
 tensor([[[[1470., 1519., 1568.],
           [1911., 1960., 2009.],
           [2352., 2401., 2450.]]]]))

In [195]:
fet.shape

torch.Size([1, 7, 7])

In [188]:
torch.conv2d(torch.zeros(1,7,7),torch.zeros(1,1,9,9),padding="valid")

RuntimeError: Calculated padded input size per channel: (7 x 7). Kernel size: (9 x 9). Kernel size can't be greater than actual input size

In [197]:
img,fet

(tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23., 24., 25., 26.],
          [27., 28., 29., 30., 31., 32., 33., 34., 35.],
          [36., 37., 38., 39., 40., 41., 42., 43., 44.],
          [45., 46., 47., 48., 49., 50., 51., 52., 53.],
          [54., 55., 56., 57., 58., 59., 60., 61., 62.],
          [63., 64., 65., 66., 67., 68., 69., 70., 71.],
          [72., 73., 74., 75., 76., 77., 78., 79., 80.]]], requires_grad=True),
 tensor([[[ 528.,  564.,  600.,  636.,  672.,  708.,  744.],
          [ 852.,  888.,  924.,  960.,  996., 1032., 1068.],
          [1176., 1212., 1248., 1284., 1320., 1356., 1392.],
          [1500., 1536., 1572., 1608., 1644., 1680., 1716.],
          [1824., 1860., 1896., 1932., 1968., 2004., 2040.],
          [2148., 2184., 2220., 2256., 2292., 2328., 2364.],
          [2472., 2508., 2544., 2580., 2616., 2652., 2688.]]],
        grad_fn=<SqueezeBackward1>)

In [3]:
img = torch.tensor(torch.arange(1 * 9 * 9).reshape(1,9,9),requires_grad=True,dtype=torch.float32)
ker = torch.tensor(torch.arange(1 * 3 * 3).reshape(1,1,3,3),requires_grad=True,dtype=torch.float32)
fet = torch.conv2d(img,ker,stride=2,dilation=1)
x = fet.sum(0).sum(0).sum(0)
x.backward()
img.grad,img.grad.shape,ker.grad
fet

/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_57611/3913852475.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  img = torch.tensor(torch.arange(1 * 9 * 9).reshape(1,9,9),requires_grad=True,dtype=torch.float32)
/var/folders/8v/r6tfrh3s0y16r9dl8fzkgdgw0000gp/T/ipykernel_57611/3913852475.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  ker = torch.tensor(torch.arange(1 * 3 * 3).reshape(1,1,3,3),requires_grad=True,dtype=torch.float32)


tensor([[[ 528.,  600.,  672.,  744.],
         [1176., 1248., 1320., 1392.],
         [1824., 1896., 1968., 2040.],
         [2472., 2544., 2616., 2688.]]], grad_fn=<SqueezeBackward1>)